# ============================================================================
# Vajra OS — Calamares bootloader config
# ============================================================================
---
efiBootLoader: "grub"

kernel: "/boot/vmlinuz"

initramfs: "/boot/initrd.img"

initramfsName: "initrd.img"

grubInstallVariant: "efi-amd64"

grubKernelEntry: "Vajra OS"

grubTimeout: "5"

additionalInstallDirs:
  - /usr/share/secureboot

enableLuksAutomatedPrompting: false
