# ============================================================================
# Vajra OS — Calamares display manager config
# ============================================================================
---
displaymanagers:
  - gdm3

defaultDesktopEnvironment:
  desktopFile: "gnome"
  executable: "gnome-session"

basicSetup: false

sysconfigSetup: false
