# ============================================================================
# Vajra OS — Calamares user creation config
# ============================================================================
---
defaultGroups:
  - users
  - vajra-admin
  - sudo
  - cdrom
  - audio
  - video
  - plugdev
  - netdev

userShell: /bin/bash

setRootPassword: false

doAutologin: false

doReusePassword: true

doNewGroups: true

passwordRequirements:
  minLength: 6
  maxLength: 100

allowWeakPasswords: true

allowWeakPasswordsDefault: false

hostname:
  location: EtcFile
  writeHostsFile: true
  setHostname: "vajra-os"

presets:
  fullName:
    value: "Vajra User"
  loginName:
    value: "vajra"
